/*

DAY 3 NOTES

Data Visualizations & Storytelling

Data Visualization is an interdisciplinary field that combines computer science, graphic design and statistics to communicate (mostly quantitative) data or information.Data visualization is the translation of datasets into a meaningful and easy-to-understand visual medium. It’s incredibly useful for those companies that are dealing with tons of big data. Data visualizations are dynamic and often built using various programming languages including JavaScript, D3.js, CSS and HTML.

Color can be a powerful tool for data visualization designers to convey meaning and clarity when displaying data. It’s crucial, however, that designers understand how color works and what it does and doesn’t do well.


*/